// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuiviVaccinCovidCodeFirst.Modeles;

namespace SuiviVaccinCovidCodeFirst.Migrations
{
    [DbContext(typeof(VaccinContext))]
    [Migration("20220127150450_AjoutTableTypeVaccin")]
    partial class AjoutTableTypeVaccin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.TypeVaccin", b =>
                {
                    b.Property<int>("TypeVaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeVaccinId");

                    b.ToTable("TypesVaccin");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Vaccin", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAMPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeVaccinId")
                        .HasColumnType("int");

                    b.HasKey("VaccinId");

                    b.HasIndex("TypeVaccinId");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Vaccin", b =>
                {
                    b.HasOne("SuiviVaccinCovidCodeFirst.TypeVaccin", "Type")
                        .WithMany()
                        .HasForeignKey("TypeVaccinId");
                });
#pragma warning restore 612, 618
        }
    }
}
