// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuiviVaccinCovidCodeFirst.Modeles;

#nullable disable

namespace SuiviVaccinCovidCodeFirst.Migrations
{
    [DbContext(typeof(VaccinsContext))]
    [Migration("20230110020252_VaccinDevientDoseBis")]
    partial class VaccinDevientDoseBis
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Dose", b =>
                {
                    b.Property<int>("DoseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoseId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("NAMPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaccinId")
                        .HasColumnType("int");

                    b.HasKey("DoseId");

                    b.HasIndex("VaccinId");

                    b.ToTable("Doses");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Immunisation", b =>
                {
                    b.Property<int>("ImmunisationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImmunisationID"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMPatient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VaccinId")
                        .HasColumnType("int");

                    b.HasKey("ImmunisationID");

                    b.HasIndex("VaccinId");

                    b.ToTable("Immunisations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Immunisation");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Vaccin", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaccinId"), 1L, 1);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VaccinId");

                    b.ToTable("Vaccins");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Covid19", b =>
                {
                    b.HasBaseType("SuiviVaccinCovidCodeFirst.Modeles.Immunisation");

                    b.Property<string>("Variant")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Covid19");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Dose", b =>
                {
                    b.HasOne("SuiviVaccinCovidCodeFirst.Modeles.Vaccin", "Vaccin")
                        .WithMany()
                        .HasForeignKey("VaccinId");

                    b.Navigation("Vaccin");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Immunisation", b =>
                {
                    b.HasOne("SuiviVaccinCovidCodeFirst.Modeles.Vaccin", null)
                        .WithMany("Immunisations")
                        .HasForeignKey("VaccinId");
                });

            modelBuilder.Entity("SuiviVaccinCovidCodeFirst.Modeles.Vaccin", b =>
                {
                    b.Navigation("Immunisations");
                });
#pragma warning restore 612, 618
        }
    }
}
